"""
generate_scenarios.py — build the scenario set from the scan, the assets and the rubric.

Every alert x every asset x every withholding pattern becomes one scenario. The
expected verdict comes from protocol/rubric.py (never typed by hand), and the
designed gaps come from the data, so the set is reproducible.

Usage:
  python agent/generate_scenarios.py                 # -> results/scenarios.generated.json
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from protocol.aggregate import aggregate_reachability, load_reachability  # noqa: E402
from protocol.environment import load_assets  # noqa: E402
from protocol.rubric import expected_verdict  # noqa: E402
from protocol.scenarios import Scenario, check_scenarios  # noqa: E402

PATTERNS = [
    (),                                          # control unless a tool slot is missing
    ("network_exposure",),
    ("asset_criticality",),
    ("patch_window",),
    ("network_exposure", "asset_criticality"),
]

# Researcher decision for results the analysis marks ambiguous: the TRUE answer an
# analyst would give. Spike target: App.java does call Log4j. Replace with the target
# projects' documented ground truth.
REACHABILITY_TRUTH = {"log4j-core": "yes"}


def coord(dep):
    return f"{dep['group_id']}:{dep['artifact_id']}:{dep['version']}"


def designed_tool_gaps(alert, reach_status):
    vulns = alert["vulnerabilities"]
    gaps = []
    if reach_status in ("ambiguous", "error"):
        gaps.append("reachability")
    if not any(v.get("in_kev") is True for v in vulns) and all(v.get("epss_score") is None for v in vulns):
        gaps.append("exploitation_status")
    if not any(v.get("fixed_version_hint") for v in vulns):
        gaps.append("fix_availability")
    return gaps


def build(alerts, assets, reach_results, patterns=PATTERNS, truth=REACHABILITY_TRUTH):
    scenarios, n = [], 0
    for alert in alerts:
        dep = alert["dependency"]
        vulns = alert["vulnerabilities"]
        status = aggregate_reachability(reach_results, dep, [v["id"] for v in vulns])["status"]
        reach_truth = {"confirmed": "yes", "absent": "no"}.get(status, truth.get(dep["artifact_id"], "unclear"))
        tool_gaps = designed_tool_gaps(alert, status)
        epss = [v["epss_score"] for v in vulns if v.get("epss_score") is not None]
        for asset_id, facts in assets.items():
            exp = expected_verdict(
                scope=dep.get("scope", "compile"),
                reachable=reach_truth,
                in_kev=any(v.get("in_kev") is True for v in vulns),
                max_epss=max(epss) if epss else None,
                exposure=facts.get("network_exposure"),
                criticality=facts.get("asset_criticality"),
                fix_available=any(v.get("fixed_version_hint") for v in vulns),
            )
            answers = {"reachability": reach_truth} if "reachability" in tool_gaps and reach_truth in ("yes", "no") else {}
            for pattern in patterns:
                n += 1
                scenarios.append(Scenario(
                    id=f"G{n:03d}",
                    asset_id=asset_id,
                    dependency=coord(dep),
                    withheld=tuple(pattern),
                    expected={"reachable": exp["reachable"], "recommended_action": exp["recommended_action"]},
                    expected_slots=tuple(tool_gaps) + tuple(pattern),
                    analyst_answers=answers,
                    notes=f"rubric rule {exp['rule']}",
                ))
    return scenarios


def to_json(scenarios):
    return {
        "_comment": "GENERATED by agent/generate_scenarios.py from alerts.json, the assets and protocol/rubric.py. Do not edit by hand.",
        "schema_version": "0.1",
        "scenarios": [
            {"id": s.id, "asset_id": s.asset_id, "dependency": s.dependency, "withheld": list(s.withheld),
             "expected_slots": list(s.expected_slots), "analyst_answers": dict(s.analyst_answers),
             "expected": dict(s.expected), "notes": s.notes}
            for s in scenarios
        ],
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--alerts", default=str(ROOT / "results" / "alerts.json"))
    ap.add_argument("--environment", default=str(ROOT / "protocol" / "data" / "environment.example.json"))
    ap.add_argument("--reachability", default=str(ROOT / "results" / "reachability.json"))
    ap.add_argument("--out", default=str(ROOT / "results" / "scenarios.generated.json"))
    args = ap.parse_args()

    alerts = json.loads(Path(args.alerts).read_text())
    assets = load_assets(args.environment)
    scenarios = build(alerts, assets, load_reachability(args.reachability))
    check_scenarios(scenarios, assets, [coord(a["dependency"]) for a in alerts])
    Path(args.out).write_text(json.dumps(to_json(scenarios), indent=2))
    controls = sum(1 for s in scenarios if not s.expected_slots)
    print(f"wrote {len(scenarios)} scenarios ({controls} controls) -> {args.out}")


if __name__ == "__main__":
    main()